# Generated by Django 3.1.6 on 2021-04-17 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoteApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='likes',
            new_name='users_who_liked',
        ),
    ]
